#!/usr/bin/env bash
# ==============================================================================
# TakinMart E-Commerce — Automated Turnkey VPS & aaPanel Installer
# Auto-detects ports, generates .env, auto-initializes PostgreSQL DB, starts Docker
# ==============================================================================

set -eo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$APP_DIR"

log_info() { echo -e "${BLUE}[INFO]${NC} $1" >&2; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1" >&2; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1" >&2; }
log_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

clear || true
echo -e "${CYAN}${BOLD}"
cat << "EOF"
  _____     _    _       __  __            _   
 |_   _|_ _| | _(_)_ __ |  \/  |__ _ _ _ _| |_ 
   | |/ _` | |/ / | '_ \| |\/| / _` | '_|_   _|
   |_|\__,_|_|\_\_|_| |_|_|  |_\__,_|_|   |_|  
     Bhutan Artisan E-Commerce Platform
EOF
echo -e "${NC}"
echo -e "${BOLD}==============================================================================${NC}"
echo -e " 🚀 Production Installer for aaPanel, Cloud VPS, and Dedicated Servers"
echo -e " 🔒 Auto Database Provisioning & Zero Port-Collision Docker Engine"
echo -e "${BOLD}==============================================================================${NC}\n"

# 1. Check root or sudo
if [ "$EUID" -ne 0 ]; then
    log_warn "Running without root privileges. If docker requires sudo, please run as root or with sudo."
fi

# 2. Check Docker and Docker Compose
log_info "[1/5] Checking Docker prerequisites..."
if ! command -v docker >/dev/null 2>&1; then
    log_error "Docker is not installed! Please install Docker Manager in aaPanel App Store or run: curl -fsSL https://get.docker.com | sh"
    exit 1
fi

COMPOSE_CMD=""
if docker compose version >/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE_CMD="docker-compose"
else
    log_error "Docker Compose is required but not installed."
    exit 1
fi
log_success "Docker & Docker Compose detected: $($COMPOSE_CMD version)"

# 3. Port conflict detection & automatic remapping
log_info "[2/5] Scanning for available ports..."
check_port() {
    local port=$1
    if command -v ss >/dev/null 2>&1; then
        ss -tuln | grep -q ":${port} " && return 1 || return 0
    elif command -v netstat >/dev/null 2>&1; then
        netstat -tuln | grep -q ":${port} " && return 1 || return 0
    else
        (echo > /dev/tcp/127.0.0.1/$port) >/dev/null 2>&1 && return 1 || return 0
    fi
}

find_free_port() {
    local base=$1
    local port=$base
    while ! check_port $port; do
        log_warn "Port $port is already in use by host. Trying next port..."
        port=$((port + 1))
    done
    echo $port
}

WEB_PORT=$(find_free_port 3000)
POSTGRES_PORT=$(find_free_port 5432)
log_success "Assigned Web Port: $WEB_PORT"
log_success "Assigned PostgreSQL Port: $POSTGRES_PORT"

# 4. Generate .env file if missing
log_info "[3/5] Setting up environment configuration (.env)..."
if [ ! -f ".env" ]; then
    RAND_PASS=$(openssl rand -hex 16 2>/dev/null || date +%s%N | md5sum | head -c 24)
    cat > .env << ENVEOF
# Auto-generated by TakinMart Installer
WEB_PORT=${WEB_PORT}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_USER=takin_admin
POSTGRES_PASSWORD=${RAND_PASS}
POSTGRES_DB=takinmart_db
APP_URL=https://takinmart.bt
DATABASE_URL=postgresql://takin_admin:${RAND_PASS}@127.0.0.1:${POSTGRES_PORT}/takinmart_db
ENVEOF
    log_success "Created .env with secure random PostgreSQL credentials!"
else
    log_info "Existing .env found. Ensuring assigned ports are set..."
    grep -q '^WEB_PORT=' .env && sed -i "s/^WEB_PORT=.*/WEB_PORT=${WEB_PORT}/" .env || echo "WEB_PORT=${WEB_PORT}" >> .env
    grep -q '^POSTGRES_PORT=' .env && sed -i "s/^POSTGRES_PORT=.*/POSTGRES_PORT=${POSTGRES_PORT}/" .env || echo "POSTGRES_PORT=${POSTGRES_PORT}" >> .env
fi

# 5. Build and Launch Containers
log_info "[4/5] Building and launching application & PostgreSQL containers..."
$COMPOSE_CMD -f docker-compose.aapanel.yaml up -d --build

# 6. Verify Database Initialization
log_info "[5/5] Verifying PostgreSQL database initialization..."
sleep 5
for i in {1..10}; do
    if docker exec takinmart_postgres pg_isready -U takin_admin -d takinmart_db >/dev/null 2>&1; then
        log_success "PostgreSQL is healthy and database 'takinmart_db' is initialized!"
        break
    fi
    echo -n "."
    sleep 2
done

echo ""
echo -e "${GREEN}${BOLD}==============================================================================${NC}"
echo -e "${GREEN}${BOLD} ✔ TakinMart E-Commerce Platform successfully installed and running!${NC}"
echo -e "${GREEN}${BOLD}==============================================================================${NC}"
echo -e "  🌐 Web App Local URL:      http://127.0.0.1:${WEB_PORT}"
echo -e "  🗄️  PostgreSQL Host URL:   127.0.0.1:${POSTGRES_PORT} (DB: takinmart_db)"
echo -e "${BOLD}==============================================================================${NC}"
echo ""
echo -e "${CYAN}${BOLD}📋 NEXT STEP: Configure aaPanel Website & SSL (Takes 1 minute):${NC}"
echo -e " 1. In aaPanel, go to: ${BOLD}Website${NC} -> ${BOLD}Add Site${NC}"
echo -e "    - Domain: your domain (e.g. takinmart.bt)"
echo -e "    - Database: None (managed by Docker)"
echo -e " 2. In Site Settings -> ${BOLD}SSL${NC} -> Enable Let's Encrypt SSL & Force HTTPS"
echo -e " 3. In Site Settings -> ${BOLD}Reverse Proxy${NC} -> Add Reverse Proxy:"
echo -e "    - Proxy Name: takinmart_proxy"
echo -e "    - Target URL: ${BOLD}http://127.0.0.1:${WEB_PORT}${NC}"
echo -e " 4. Click Save. Your website is live with HTTPS!"
echo ""
