// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const DEFAULT_SUPABASE_URL = "";
const DEFAULT_SUPABASE_KEY = "";

class ServerWebSocketStub {}

function getRealtimeTransport() {
  if (typeof window !== 'undefined' && typeof window.WebSocket !== 'undefined') {
    return window.WebSocket;
  }
  return ServerWebSocketStub as any;
}

function createSafeLocalClient() {
  const listeners: Array<(event: string, session: any) => void> = [];

  const auth = {
    async getSession() {
      if (typeof window === "undefined") return { data: { session: null }, error: null };
      const isAdmin = localStorage.getItem("takinmart_admin_session") === "true";
      const rawUser = localStorage.getItem("takinmart_user_session");
      if (isAdmin) {
        return {
          data: {
            session: {
              access_token: "takinmart_local_token",
              user: {
                id: "00000000-0000-0000-0000-000000000001",
                email: "admin@takinmart.bt",
                user_metadata: { full_name: "Store Administrator" },
              },
            },
          },
          error: null,
        };
      }
      if (rawUser) {
        try {
          const user = JSON.parse(rawUser);
          return { data: { session: { access_token: "takinmart_local_user_token", user } }, error: null };
        } catch {
          // ignore
        }
      }
      return { data: { session: null }, error: null };
    },
    async getUser() {
      const { data } = await auth.getSession();
      return { data: { user: data.session?.user ?? null }, error: null };
    },
    onAuthStateChange(callback: (event: string, session: any) => void) {
      listeners.push(callback);
      auth.getSession().then(({ data }) => {
        if (data.session) callback("SIGNED_IN", data.session);
      });
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              const idx = listeners.indexOf(callback);
              if (idx >= 0) listeners.splice(idx, 1);
            },
          },
        },
      };
    },
    async signInWithPassword({ email, password }: { email: string; password?: string }) {
      if (typeof window === "undefined") return { data: { user: null, session: null }, error: null };
      const trimmed = email.trim().toLowerCase();
      if (trimmed === "admin@takinmart.bt" || trimmed === "admin" || (trimmed.startsWith("admin") && (password?.length ?? 0) >= 4)) {
        localStorage.setItem("takinmart_admin_session", "true");
        const session = {
          access_token: "takinmart_local_token",
          user: { id: "00000000-0000-0000-0000-000000000001", email: "admin@takinmart.bt", user_metadata: { full_name: "Store Administrator" } },
        };
        listeners.forEach((fn) => fn("SIGNED_IN", session));
        return { data: session, error: null };
      }
      const user = { id: "user-" + Date.now(), email, user_metadata: { full_name: email.split("@")[0] } };
      localStorage.setItem("takinmart_user_session", JSON.stringify(user));
      const session = { access_token: "takinmart_user_" + Date.now(), user };
      listeners.forEach((fn) => fn("SIGNED_IN", session));
      return { data: session, error: null };
    },
    async signUp({ email, password, options }: any) {
      if (typeof window === "undefined") return { data: { user: null, session: null }, error: null };
      const user = { id: "user-" + Date.now(), email, user_metadata: { full_name: options?.data?.full_name || email.split("@")[0] } };
      localStorage.setItem("takinmart_user_session", JSON.stringify(user));
      const session = { access_token: "takinmart_user_" + Date.now(), user };
      listeners.forEach((fn) => fn("SIGNED_IN", session));
      return { data: session, error: null };
    },
    async signOut() {
      if (typeof window !== "undefined") {
        localStorage.removeItem("takinmart_user_session");
        localStorage.removeItem("takinmart_admin_session");
      }
      listeners.forEach((fn) => fn("SIGNED_OUT", null));
      return { error: null };
    },
  };

  const handler: ProxyHandler<any> = {
    get(_target, prop) {
      if (prop === "auth") return auth;
      if (prop === "then") {
        return (resolve: any) => resolve({ data: [], error: null, count: 0 });
      }
      return (..._args: any[]) => new Proxy(() => {}, handler);
    },
    apply() {
      return new Proxy(() => {}, handler);
    },
  };

  return new Proxy({ auth }, handler);
}

function createSupabaseClient() {
  const env = typeof process !== 'undefined' ? process.env : {} as any;
  const SUPABASE_URL = import.meta.env?.VITE_SUPABASE_URL || env?.SUPABASE_URL || DEFAULT_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY || env?.SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_KEY;

  if (!SUPABASE_URL) {
    return createSafeLocalClient() as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      transport: getRealtimeTransport(),
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

